name: Semantic Release

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  dry:
    name: dry release
    uses: mathieu-keller/github-action-workflows/.github/workflows/semantic-release.yaml@main
    if: ${{ github.ref != 'refs/heads/main' }}
    with:
      release-branch: main
      dry: true
  release:
    name: create release
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: mathieu-keller/github-action-workflows/.github/workflows/semantic-release.yaml@main
    with:
      release-branch: main
      dry: false